
services:
  redis_service:
    build:
      context: redis-service
      dockerfile: Dockerfile
    container_name: redis-server
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data
    restart: always
  app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - 4400:4400
    depends_on:
      - redis_service
    env_file:
      - .env

volumes:
  redis-data: